os: linux
dist: trusty
language: java
jdk: oraclejdk8

services:
  - docker

env:
  - XATKIT_DEV=$TRAVIS_BUILD_DIR XATKIT=$TRAVIS_BUILD_DIR/build
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - nvm install node # "node" is an alias for the latest version. we may need to install a specific version
  - travis_wait 45 bash .util/build_xatkit.sh # the job expires after 45 mins
  - docker build -t xatkit/xatkit-core .
before_script:
  - docker run -d -p 5000:5000 -p 5001:5001 --name greetings-bot xatkit/xatkit-core
  - cd tests/greetings
  - npm install
  - sleep 15 # we give some time to Xatkit to start
script:
  - npm test

deploy:
  provider: script
  script: bash .util/docker_push.sh

notifications:
  email: no
