os: linux
dist: trusty
language: java
jdk: oraclejdk8

services:
  - docker

env:
  global:
    - XATKIT_DEV=$TRAVIS_BUILD_DIR XATKIT=$TRAVIS_BUILD_DIR/build
    - secure: eahBK6CabfSEYxwS9KSxkkEh/zMrxNt0nnrrgMyRu605kR4vHGBaIDUamZKkQprufS7UFSJr5ApuOGGgYLmC9TYifJqV+7BbcPb6Xr0B8WPjQuXgHi7+as3YYIuUTQ6xTtzqwUztERZJT+tSH5vZIi2C87R6vj9S79JRfoVNweFQ8HexT9zmOZXMiFLcMhKuowhDKXJ0fB/c6DdvulskC+xDo7oDx62n/W7Kwl7WY/PMl3+LZUZ+0Mb4y2/eocAVE8pYkJArDqO6/SHhlEr/NZ5laUVtb0oGXrvmdqxXCDDPqWSLEXso7/16LTcyh7Pw4f5NKrir5saa0GT/LgbyJX1fQfSoycSDpXcL9hVbFWO8QnhrAM+VnDmMFXXQkmIiScSg74PKlfZtVaOjHyDNt9RiN4Vrl/JrRx7I6BGNpBs08jxq6HM7yScZ1d3ZIRzDaN0jT3lNW3opky1xnzz2TIfrBy4ABGNsxEq8D+fjmlX7MhM59Mt29cxCwVYPKZxE3p1xwgeylN+YfzbmwTxBfypXvzP8UP6R5UE/SYd0o+ZZCKRPuryv2LQ+gyXp5wJ9qM13yKjFoOke+1dvFadT8UZoUmtcSjtAOHDyonwdikW1QpfMfFgTY1Y7eD6hxFWr1X0MraRIkN0hLenzmTzCyoSNJWCJ/VhzhFVw2iycdnU=
    - secure: DhgoFf7TrF51i+XWwj0OkOvA+SlHa7OEtoGQACfo2+c0ccrhDYxX+RqgSvw62DkSC9wWECqwyBakaEljxOGTTFHmcTLh5ZQHCghnugIX0sjwx4Oya4OjXjrLW1O7CPtvYKg89lYXKHQVTnsX3MkMZG7N7Qn3R3x/Xx2Y74EhmTQ3juIpLJKIjhwy2pIkTDxvyp+aAHdvTxO1H0qdBRU/dt2X/ArfrtaTwDmTmwCAbgLfog42xrB3rPfm6dvzc55PWg0hBLfiFnK34yVAfpjrPOczgr/DMd1Dn+SG7VwWrJ3HKXyAZtFoqwuFcAnOK4YouI5nguZsGtSUY/EFCBQ5C8fX/ODMoWWENKQHKl2C/k/P9U0OxG/hEF5QiBVpyWn548k3vM2zO7mdxGrhTF2X4phy7atMWkhLMnTKEBx1I6EuHo4zg8xFAL40Xl6UynSlSI21+LDtC0zaTqLqYAEjRhaFcSN8Dlz0AdvmsrsfG4YsLwz/IztfRcN7M9azphi5s1mUrOQaQoayz0eGrkWkrQmddpfH+Ydz5IkkAw94lkk1/QyNegVpM9FeZKjfsHW5GH8NmM5261VDm3SaH/jGtD3DrHs34XMhG8z99OdG273FtyxX3Mk6Gxf5Sn5PSBremgyeDBmYJkzk98+AaDjkkVbIqESZuHSVxCFmpqaId5E= 
    
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - nvm install node # "node" is an alias for the latest version. we may need to install a specific version
  - travis_wait 45 bash .util/build_xatkit.sh # the job expires after 45 mins
  - docker build -t xatkit/xatkit-core .
before_script:
  - docker run -d -p 5000:5000 -p 5001:5001 --name greetings-bot xatkit/xatkit-core
  - cd tests/greetings
  - npm install
  - sleep 15 # we give some time to Xatkit to start
script:
  - npm test

before_deploy:
  - cd $XATKIT_DEV

deploy:
  skip_cleanup: true
  provider: script
  script: bash .util/docker_push.sh
  on:
    all_branches: true # we need to modify this in the future to only deploy when a certain condition is met

notifications:
  email: no
